backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/admin/media" # Media files will be stored in the repo under static/images/uploads
public_folder: "/admin/media" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/blog
    label: "Docs" # Used in the UI
    folder: "src/prose" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish", name: "publish", widget: "boolean"}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, options: ["UI logic", "Composition functions", "Components", "Configuration utilities"]}
      - {label: "Body", name: "body", widget: "markdown", required: true}
